export const tableData = [
    {
        checkbox: "false",
        number: "INC0000001",
        opened: "2020-01-25",
        shortdescription: "Can't read email",
        caller: "Fred Luddy",
        priority: "Low",  // Updated to capitalized form
        state: "On Hold",
        category: "Network",
        group: "Service Desk",
        assigned: "Charlie Witherspoon",
        updated: "2020-06-02",
        updatelist: "admin"
    },
    {
        checkbox: "false",
        number: "INC0000002",
        opened: "2020-01-19",
        shortdescription: "Forgot email password",
        caller: "Fred Luddy",
        priority: "Low",
        state: "Closed",
        category: "Network",
        group: "Network",
        assigned: "Howard Johnson",
        updated: "2020-04-26",
        updatelist: "admin"
    },
    {
        checkbox: "false",
        number: "INC0000003",
        opened: "2020-01-26",
        shortdescription: "Network file shares",
        caller: "Joe Employee",
        priority: "High",
        state: "In Progress",
        category: "Hardware",
        group: "Hardware",
        assigned: "David Loo",
        updated: "2022-04-05",
        updatelist: "system"
    },
    {
        checkbox: "false",
        number: "INC0000004",
        opened: "2020-01-16",
        shortdescription: "Reset my password",
        caller: "Joe Employee",
        priority: "Low",
        state: "In Progress",
        category: "Software",
        group: "Software",
        assigned: "User",
        updated: "2022-04-05",
        updatelist: "admin"
    },
    {
        checkbox: "false",
        number: "INC0000005",
        opened: "2020-01-10",
        shortdescription: "CPU load high",
        caller: "Fred Luddy",
        priority: "Moderate",
        state: "Closed",
        category: "Network",
        group: "Network",
        assigned: "User",
        updated: "2022-04-05",
        updatelist: "admin"
    },
    {
        checkbox: "false",
        number: "INC0000006",
        opened: "2020-01-10",
        shortdescription: "CPU load high",
        caller: "Fred Luddy",
        priority: "Moderate",
        state: "Closed",
        category: "Network",
        group: "Network",
        assigned: "User",
        updated: "2022-04-05",
        updatelist: "admin"
    }
];
